package com.meam.kaffa.student.constants

object StudentCustomeFields {
    val ROLL_NUMBER = "ROLLNUMBER"
    val GRADE = "GRADE"
    val DIVISION = "DIVISION"
    val REGISTRATION_DATE = "REGISTRATIONDATE"
    val FATHER_NAME = "FATHERNAME"
    val MOTHER_NAME = "MOTHERNAME"
    val GUARDIAN_NAME = "GUARDIANNAME"
    val FATHER_MOBILE_NUMBER = "FATHERMOBILENUMBER"
    val MOTHER_MOBILE_NUMBER = "MOTHERMOBILENUMBER"
    val GUARDIAN_MOBILE_NUMBER = "GUARDIANMOBILENUMBER"
    val NATIONALITY = "NATIONALITY"
    val LANGUAGE_SPOKEN = "LANGUAGESPOKEN"
}
