server:
  port: 8080
  shutdown: "graceful"
spring:
  application:
    name: "notification"
  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        enable_lazy_load_no_trans: "true"
        jdbc:
          lob:
            non_contextual_creation: "true"
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/kaffa_notification?sslmode=${PG_SSLMODE}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:root}"
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:50}
  kafka:
    url: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      group-id: wp-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: meamscheduler@gmail.com
    password: euydbdmuohxmyrht
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    suffix: .html
    template-loader-path: classpath:templates/
notification:
  from: support@approval-sys.com
  server_url: ${SERVER_URL:http://localhost:8080}
eureka:
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    healthcheck:
      enabled: true
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: "true"
  endpoints:
    health:
      sensitive: "true"
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    org:
      springframework:
        security: DEBUG
ums:
  service:
    name: "ums"
    url: "http://localhost:8052"
