package com.meam.kaffa.security.constants

object RoleConstants {
    const val ROLE_VIEW_DASHBOARD = "ROLE_VIEW_DASHBOARD"
    const val ROLE_READ_TEACHERS = "ROLE_READ_TEACHERS"
    const val ROLE_WRITE_TEACHERS = "ROLE_WRITE_TEACHERS"
    const val ROLE_READ_STUDENTS = "ROLE_READ_STUDENTS"
    const val ROLE_WRITE_STUDENTS = "ROLE_WRITE_STUDENTS"
    const val ROLE_READ_STAFF = "ROLE_READ_STAFF"
    const val ROLE_WRITE_STAFF = "ROLE_WRITE_STAFF"
    const val ROLE_READ_FEES = "ROLE_READ_FEES"
    const val ROLE_WRITE_FEES = "ROLE_WRITE_FEES"
    const val ROLE_READ_INVOICES = "ROLE_READ_INVOICES"
    const val ROLE_WRITE_INVOICES = "ROLE_WRITE_INVOICES"
    const val ROLE_READ_ATTENDANCE = "ROLE_READ_ATTENDANCE"
    const val ROLE_WRITE_ATTENDANCE = "ROLE_WRITE_ATTENDANCE"
    const val ROLE_READ_PERFORMANCE = "ROLE_READ_PERFORMANCE"
    const val ROLE_WRITE_PERFORMANCE = "ROLE_WRITE_PERFORMANCE"
    const val ROLE_READ_USER_MANAGEMENT = "ROLE_READ_USER_MANAGEMENT"
    const val ROLE_WRITE_USER_MANAGEMENT = "ROLE_WRITE_USER_MANAGEMENT"
    const val ROLE_READ_ROLE = "ROLE_READ_ROLE"
    const val ROLE_WRITE_ROLE = "ROLE_WRITE_ROLE"
    const val ROLE_SUPREME_ADMIN = "ROLE_SUPREME_ADMIN"
}